
- id: 689fab90-2ba0-4d03-9342-5554d11d54be
  name: Administrator
  icon: verified
  description: Initial administrative role with unrestricted App/API access
  app_access: true
  admin_access: true

- id: 7e3ac987-8a62-409f-8f3c-639cfdeb3568
  name: Unassigned
  icon: question_mark
  description: Default role to assign new users logging in via auth0

- id: 901ead82-3e1e-4b81-a876-0b36638ff1d9
  name: BCC Event Manager
  icon: support_agent
  app_access: true

- id: aa37ee67-b2b6-4ffa-8987-a9f7ae86be51
  name: Activity Coordinator
  icon: manage_accounts
  app_access: true

- id: ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6
  name: ApiWriter
  icon: supervised_user_circle

- id: ce23293b-3719-435a-aa6d-e9efa90adf83
  name: BUK Admin
  icon: supervised_user_circle
  app_access: true
